### ISSUE TITLE
Warning: setState(...): You passed an undefined or null state object; instead, use forceUpdate().

### ISSUE THREAD

**Issue by victorkane** [awebfactory/react-starter#2]
This warning occurs when viewing individual docs (Menu item Docs, then clicking on a link to a specific doc).

In [blog post announcing release v0.14](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html) breaking changes for v0.15 are pointed out via warnings:

> Every new change in 0.14, including the major changes below, is introduced with a runtime warning and will work as before until 0.15, so you don't have to worry about your app breaking with this upgrade.

Even though this warning is not mentioned, and the code works flawlessly, it behooves us to find out why this warning is being generated, and what forceUpdate is.

The go to doc is [Component API. React.Component](https://facebook.github.io/react/docs/component-api.html), specifically [forceUpdate](https://facebook.github.io/react/docs/component-api.html#forceupdate).
- [ ] one

**Comment by victorkane** [comment]
Well [forceUpdate](https://facebook.github.io/react/docs/component-api.html#forceupdate) doesn't work (doesn't force an update)... will continue to explore.

**Comment by mymickey** [comment]
+1

**Comment by victorkane** [comment]
Solved by reworking of component composition in current Master branch
